---
- name: restart wazuh-agent
  debug:
    msg: "Here would be a handler to restart the wazuh-agent service."
    # service: name=wazuh-agent state=restarted enabled=yes

- name: Windows | Restart Wazuh Agent
  win_service: name=WazuhSvc start_mode=auto state=restarted

- name: macOS | Restart Wazuh Agent
  command: /Library/Ossec/bin/wazuh-control restart