---
- block:
  - name: Copy Filebeat configuration.
    template:
      src: filebeat.yml.j2
      dest: "/etc/filebeat/filebeat.yml"
      owner: root
      group: root
      mode: 0400
    notify: restart filebeat

  - name: Fetch latest Wazuh alerts template
    get_url:
      url: "{{ wazuh_template_url }}"
      dest: "/etc/filebeat/wazuh-template.json"
      owner: root
      group: root
      mode: 0400
    notify: restart filebeat

  tags:
  - configure
